default: PerfectPet.class Serializer.class PerfectPetApplication.class

PerfectPet.class: PerfectPet.java
	javac PerfectPet.java

Serializer.class: Serializer.java
	javac Serializer.java

PerfectPetApplication.class: PerfectPetApplication.java
	javac PerfectPetApplication.java

clean:
	rm *.class *.ser

run: 
	java PerfectPetApplication
